# Create Dataset

In [4]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [5]:
from sklearn import set_config
set_config(display='diagram')

In [6]:
# we import the diabetes
X, y = load_diabetes(return_X_y=True)

In [7]:
print(f"Size of X :{X.shape} \nSize of y {y.shape}")

Size of X :(442, 10) 
Size of y (442,)


# Train Test Split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [9]:
#  I make mistake in during prediction so 
# This help me during the debugging time

print(f"Size of X_train :{X_train.shape} \nSize of y_train {y_train.shape} \n")
print(f"Size of X_test :{X_test.shape} \nSize of y_test {y_test.shape} \n")

Size of X_train :(353, 10) 
Size of y_train (353,) 

Size of X_test :(89, 10) 
Size of y_test (89,) 



# Apply Sklearn Model

In [10]:
reg = LinearRegression()

In [11]:
reg.fit(X_train, y_train)

LinearRegression()

In [12]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [13]:
reg.intercept_

np.float64(151.88331005254167)

In [14]:
y_pred = reg.predict(X_test)
y_pred.shape

(89,)

In [48]:
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [15]:
r2_score(y_test, y_pred)

0.4399338661568968

# Making own class

In [16]:
# overall structure 

class BatchGDRegressor:
    
    def __init__(self, learning_rate=0.01, epochs=100):
        pass
    def fit(self, X, y):
        pass
    def predict(self, y):
        pass

In [17]:
# we have the 10 columns 
X_train.shape[1]

10

In [18]:
# initialize all the intercept with ones
np.ones(X_train.shape[1])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### **b_0 : intercept value** 

- Y_i / y / y_train all same 
- This is known value / targeted value
  
**Step 1** 
- self.intercept_ = self.intercept_ - (self.lr * intercept_derivative)
- Now what is intercept_derivative ?
-  (-2/n) * summation(y_i - y_i_hat)
-  Now intercept_derivative is unknown 

**Step 2**
- why mean  ? 
- where is the summation and (1/n) ?
- if you notice then you got 
- due to inside the summation those are the scalar quaintly  (y_i - y_i_hat) let it k
- so now
- (-2) * (1/n)*summation(K_i)
- now it become (1/n)*summation(K_i)
- -2 * mean(k_i)
- now open k_i
- we got
- -2 * mean(y_i - y_i_hat)
- intercept_derivative = -2 * np.mean(y, y_hat)
- now y_hat is known ?
  
**Step 3 :**
- here beta_0 means self.b
- If you write the value of y_1, y_2 and y_3 
- we can create the matrix easily of 
- y_hat = [[X_11, X_12, X_13][beta_1, beta_2, beta_3]] + beta_0
- it can convert into
- np.dot(X, coef_) + beta_0

---
#### **All Coefficient derivative**

**step 1 :**
- self.coef_ = self.coef_ - (self.lr * coefficient_derivative)
- now the coefficient_derivative unknown
  
**step 2 :**
- coefficient_derivative = (-2/n) * (y - y_hat).(X_i1)
- or (-2) * ((y - y_hat).(X))/n
- here n means no of columns in the dataset (exclude the target )
- here X means X_train all data
- y - y_hat
- (y - y_hat).(X_i1) -> this is scalar
- y_hat is find from above already
- x_i1 ->. all values of the first row
- similarly for all  
- it means it is the total x_train 
- 

In [49]:
import numpy as np

class BatchGDRegressor:
    
    def __init__(self, learning_rate=0.01, epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self, X, y):
        # Initialize the coefficients and intercept
        self.intercept_ = 0
        self.coef_ = np.ones(X.shape[1])
        
        # Gradient Descent Loop
        for epoch in range(self.epochs):
            # Make predictions
            y_hat = np.dot(X, self.coef_) + self.intercept_
            
            # Calculate gradients
            intercept_derivative = -2 * np.mean(y - y_hat)
            coef_derivative = -2 * np.dot(X.T, (y - y_hat)) / X.shape[0]
            
            # Update parameters
            self.intercept_ -= self.lr * intercept_derivative
            self.coef_ -= self.lr * coef_derivative
            
            # Optionally print the parameters at each epoch (for debugging)
            # if epoch % 10 == 0:  # Print every 10 epochs
            #    print(f"Epoch {epoch}: Coefficients = {self.coef_}, Intercept = {self.intercept_}")
            
    def predict(self, X):
        # Make predictions using the learned parameters
        return np.dot(X, self.coef_) + self.intercept_


In [63]:
bgd = BatchGDRegressor(learning_rate=0.2, epochs=1000)

In [64]:
bgd.fit(X_train, y_train)  # Train the model first

In [65]:
print("Coefficients after fitting:", bgd.coef_)
print("Intercept after fitting:", bgd.intercept_)

Coefficients after fitting: [  52.54762224  -79.40819375  371.70817708  260.44192982   10.57659065
  -39.72663693 -178.23281737  128.51448579  336.87309872  128.78378765]
Intercept after fitting: 152.1124536947972


In [66]:
y_pred_own = bgd.predict(X_test)  # Now make predictions
y_pred_own

array([153.68794317, 192.38738934, 138.54601616, 108.0576446 ,
       248.03101066, 239.7162672 , 107.76921703, 114.61027921,
        92.90744459, 185.8507302 , 158.73513786, 173.15297109,
       184.30930903, 149.12335537, 259.36698308,  91.09425621,
       187.85469799, 140.49019593, 139.16146156, 138.25811661,
       134.54048154, 188.10265398, 164.92642387, 177.87538495,
       126.60465242, 220.94739922, 196.3522743 , 118.24148253,
        61.46635645, 241.42109552, 237.93849531, 118.36382964,
        73.3477918 , 108.37101442, 200.8649825 , 166.20900725,
       166.77698811, 196.17096475, 114.84187254, 234.50703349,
       136.77673073, 126.38531125, 185.82036601, 186.71629966,
       171.55073647, 145.88283818, 173.55164253, 281.80945719,
       116.31196694, 187.14708341, 239.42622836, 131.76350777,
       144.71696552, 147.53242751, 190.31845067, 111.51148384,
       152.81443626,  84.62596594, 158.72828148, 145.12189523,
       164.05025682, 170.47347759, 109.65398991, 208.22

In [67]:
r2_score(y_test, y_pred_own)

0.439323583803228