In [ ]:
# For Load the pickle files
import pickle

In [2]:
# for testing means providing the data to model 
# for prediction
import numpy as np

In [ ]:
# Open Each file 
# It take little time to load
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('models/clf.pkl', 'rb'))

In [4]:
# user Input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [5]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [6]:
test_input[:,1].reshape(1,1)

array([['male']], dtype=object)

In [ ]:
# take one column as a input 
# Sex Column
# Make sure user follow this format during input time
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\Rudra\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [8]:
test_input_sex

array([[0., 1.]])

In [ ]:
# Embarked column
# Make sure user follow this format during input time
# Pclass/gender/age/SibSp/Parch/Fare/Embarked

In [ ]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

c:\Users\Rudra\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 0.]])

In [12]:
# Age column
test_input_age = test_input[:,2].reshape(1,1)

In [ ]:
#  Make all in one 
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [13]:

test_input_transformed.shape

(1, 11)

In [ ]:
# Algorithm predict this person will live 
clf.predict(test_input_transformed)

array([1])

**Summary**

- Just think about how much time it take to make functional
- If user make any mistake then wrong ans
- If we have too many columns then 
- We slice the user input give to specific column to predict 
- then merge and 
- give all to predict the algorithm 
- too much huddle

16:47PM IST
23-04-2025