# Import data and libraries 

In [58]:
import os
import numpy as np
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [57]:
import pickle 

In [52]:
df = pd.read_csv('train.csv')
df.sample(5)

PassengerId  Survived  Pclass                            Name   Sex  \
130          131         0       3            Drazenoic, Mr. Jozef  male   
411          412         0       3                 Hart, Mr. Henry  male   
20            21         0       2            Fynney, Mr. Joseph J  male   
131          132         0       3  Coelho, Mr. Domingos Fernandeo  male   
384          385         0       3          Plotcharsky, Mr. Vasil  male   

      Age  SibSp  Parch              Ticket     Fare Cabin Embarked  
130  33.0      0      0              349241   7.8958   NaN        C  
411   NaN      0      0              394140   6.8583   NaN        Q  
20   35.0      0      0              239865  26.0000   NaN        S  
131  20.0      0      0  SOTON/O.Q. 3101307   7.0500   NaN        S  
384   NaN      0      0              349227   7.8958   NaN        S

In [10]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [12]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [13]:
df.sample(5)

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
708         1       1  female  22.0      0      0  151.5500        S
218         1       1  female  32.0      0      0   76.2917        C
759         1       1  female  33.0      0      0   86.5000        S
260         0       3    male   NaN      0      0    7.7500        Q
776         0       3    male   NaN      0      0    7.7500        Q

# Step 1: Train / Test / Split

In [15]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
# Check all columns are correct
X_train.sample()

Pclass   Sex   Age  SibSp  Parch  Fare Embarked
630       1  male  80.0      0      0  30.0        S

In [18]:
#  Null value check
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

# Applying Imputation

## Age and Embarked

In [21]:
# Create a object in the named of use column
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

# Learn the parameters
X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

# Transform the columns
X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [24]:
X_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25

## Sex and Embarked

In [28]:
# Create an object of both columns
ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Lean the Parameters
X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train[['Embarked']])

# Transform those columns
X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test[['Embarked']])

In [29]:
X_test_embarked

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],


In [31]:
# Drop the columns
X_train_rem = X_train.drop(columns=['Sex', 'Age', 'Embarked']) 
X_test_rem = X_test.drop(columns=['Sex', 'Age', 'Embarked']) 
X_test_rem.sample()

Pclass  SibSp  Parch  Fare
398       2      0      0  10.5

In [38]:
# Concatenate the all columns for algorithm
X_train_transformed = np.concatenate((X_train_rem, X_train_age,X_train_sex, X_train_embarked), axis=1)
X_test_transformed = np.concatenate((X_test_rem, X_test_age, X_test_sex, X_test_embarked), axis=1)

# Check the shape 
X_test_transformed.shape

(179, 11)

# Apply algorithm

In [39]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [40]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0])

In [42]:
accuracy_score(y_test, y_pred)

0.770949720670391

# Import the model

In [ ]:
# Create the directory if it doesn't exist
os.makedirs('models', exist_ok=True)

# Now save the files
pickle.dump(ohe_sex, open('models/ohe_sex.pkl', 'wb'))
pickle.dump(ohe_embarked, open('models/ohe_embarked.pkl', 'wb'))
pickle.dump(clf, open('models/clf.pkl', 'wb'))